# I usually use this file as a computer-specific file in my
#  .gitignore. It's pretty much because I don't understand how to set
#  up CLASSPATH well yet, and it changes between some computers.
export CLASSPATH=/usr/share/java/junit4.jar:${HOME}/s12/005/ps3/bin
JFLAGS=-g
