#! /bin/sh

TESTS=`find . -name *Test.java -print | sed 's/.\/\(.*\)/\1/g' | sed 's/\(.*\)\..*/\1/g' | sed 's/\//./g'`
FAILED=0

for f in ${TESTS}
do
    echo $f
    junit $f

    if [ $? -eq 1 ]
    then
	FAILED=1
    fi
done

if [ $FAILED -eq 1 ]
then
    echo "At least one test failed!"
fi
